### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by SrgGs** [sarfarazansari/ng4-social-login#10]
In html component is error Cannot read property 'name' of null 

html:
{{ user.name}}

**Comment by sarfarazansari** [comment]
@SrgGs  Have you define `user` object in your component.
it would be better if you use it via `*ngIf="user"`

**Comment by SrgGs** [comment]
Yes
`  private user: SocialUser;`

and the value from the object?
`console.log(user.name)`
the same error

---
`*ngIf="user"`
it works
