### ISSUE TITLE
[Facebook] Get extra user details!

### ISSUE THREAD

**Issue by abhishekdgeek** [sarfarazansari/ng4-social-login#12]
Any tip on how to fetch date of birth of user from Facebook using this plugin?

Thanks,
Abhishek.

**Comment by sarfarazansari** [comment]
@abhishekdgeek 
I don't have any plan for this and am quite busy right now.
But you can give it a try. you can fork this repo and add some more fields in `facebook-login-provider.ts` file. line no. 33 `/me?fields=name,email,picture`.

You have to douche on FB docs.
