### ISSUE TITLE
Gulp build not working

### ISSUE THREAD

**Issue by cubitworx** [sarfarazansari/ng4-social-login#13]
I am getting the following error `Error: Could not resolve './entities' from build\index.js` when trying to build the module via the gulp build command.

Please commit the npm lock file into the repo so that we can be sure what module versions were working. I am not sure if it is this or something else that is causing the problem.

**Comment by sarfarazansari** [comment]
@cubitworx I've checked it in both places (your repo and my repo).
I guess there should be needed some changes regarding making the build in your case.
I'll rewrite the logic with webpack.
