### ISSUE TITLE
Initialise only when user tried to login

### ISSUE THREAD

**Issue by cubitworx** [sarfarazansari/ng4-social-login#14]
I have forked the package to achieve what I am wanting but thought it is better place in this package.

The problem with this package at the moment is that it connects to all social providers on page load & you end up with excessive overhead & potentially conflicting authorisations.

I have removed the initialisation from load & put it in signIn

Take a look at https://github.com/cubitworx/ng4-social-login if you are interested. I am unable to test or build because I cannot get the build script working so I have just used it directly in my project & seems to be working fine.

**Comment by sarfarazansari** [comment]
@cubitworx Sorry for the delay response. I am on a vacation.
BTW Fantastic! work you've done. Am also thinking about that.
Could you please add autoLoad option in config object so will have two kinds of options available.
`{
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('Google-OAuth-Client-Id')
    preventAutoLoad: true
  }`

and wrap your code according to provided configuration.

Hope you agree.
