### ISSUE TITLE
How to add custom scope params

### ISSUE THREAD

**Issue by sdommaraju** [sarfarazansari/ng4-social-login#16]
This plugins looks good. I just need a way to pass the custom scope params for LinkedIn.

**Comment by sarfarazansari** [comment]
@sdommaraju good idea!
but currently, it is not supported in the plugin.
Also, we have to make sure from linkedin dev docs, how many kinds of scopes are supported so we can list it out.

you can fork the repo and implement this feature.
and create PR.
