### ISSUE TITLE
Feature request: rxjs 6 compliant

### ISSUE THREAD

**Issue by bjornharvold** [sarfarazansari/ng4-social-login#19]
This is one of the few libraries that still depends on rxjs-compat. Requesting that the libraries get upgrades to latest version of rxjs.

Cheers

**Comment by sarfarazansari** [comment]
@bjornharvold will do it whenever I got time BTW thanks for reminder

**Comment by sarfarazansari** [comment]
@bjornharvold [here is the updated version of library](https://github.com/sarfarazansari/ng-social-login-module)

**Comment by bjornharvold** [comment]
Thank you!
