### ISSUE TITLE
Having to click twice on the social login button before it activates

### ISSUE THREAD

**Issue by bjornharvold** [sarfarazansari/ng4-social-login#20]
This is an Angular 6 app using rxjs6

This method is bound to my HTML button:
```
signInWithFacebook(): void {
    console.log('clicked');
    observableFrom(this.authService.signIn(FacebookLoginProvider.PROVIDER_ID)).pipe(
      takeWhile(() => this.alive)
    ).subscribe((user: SocialUser) => {
      this.loginWithSocial(user);
    });
  }
```

When I click my "Login with Facebook" button, the click registers with the logger but the signIn method never actually starts. When I click the button a second time, the logger registers it again and this time, the signIn process starts with any social provider.

I switched to this, more pragmatic, approach instead of listening to authState. authState stopped reporting a successful login and I didn't have much time to look into why. I am also wrapping the Promise in an Observable as I use Observables everywhere.

Any advise would be helpful.

I am using Angular v6.0.4, Angular CLI 6.0.8 and latest ng4-social-login.

**Comment by sarfarazansari** [comment]
@bjornharvold I've not tried it yet with `angular 6`. I am unable to suggest anything currently.
i'll look into it when I got time.

**Comment by govi2010** [comment]
@bjornharvold  this project needs to be updated to RXJS 6 and Angular 6. Currently it is working on angular 4+ rxjs 5.6 i think

**Comment by federicoruf** [comment]
In my case, the solution was to change when in the AuthServiceConfig, the boolean final value to true.

**Comment by sarfarazansari** [comment]
@federicoruf here you go [https://github.com/sarfarazansari/ng-social-login-module](https://github.com/sarfarazansari/ng-social-login-module)
