### ISSUE TITLE
Application development

### ISSUE THREAD

**Issue by lgLindstrom** [sarfarazansari/ng4-social-login#3]
Hi
I am planning to use ng4-social-login but I need to understand if there is a way to "stub" function during development phase. Reason is twofold.
- I would like to avoid logging into "providers" during test phase.
- I don't understand how "providers" return link works when I am running on "localhost".

Maybe I totally have misunderstood something here,, but I really could use some help here.

//lg

**Comment by sarfarazansari** [comment]
@lgLindstrom what exactly are you looking for?

**Comment by dgpoo** [comment]
ERROR in [at-loader] ./src/app/app.module.ts:273:9 
    TS2304: Cannot find name 'provide'.

ERROR in [at-loader] ./src/app/app.module.ts:274:9 
    TS2304: Cannot find name 'useFactory'.

when i include provider then giving error above
providers: [provide: AuthServiceConfig, useFactory: provideConfig]

**Comment by sarfarazansari** [comment]
Unable to get Requirements
