### ISSUE TITLE
_this.drawUser is not a function

### ISSUE THREAD

**Issue by scozma** [sarfarazansari/ng4-social-login#4]
On page load I have this error:

`Uncaught TypeError: _this.drawUser is not a function at ng4-social-login.umd.js:318` - it seems that on the ng4-social-login.umd.js: file, ` FacebookLoginProvider.prototype.drawUser` is declared after `FacebookLoginProvider.prototype.initialize` which generates the error.
If I move `FacebookLoginProvider.prototype.drawUser` **before** `FacebookLoginProvider.prototype.initialize`, the error disappears.
Is this really a bug, or is there something I am doing wrong regarding the implementation? 
Please advise. Thanks!

**Comment by sarfarazansari** [comment]
@scozma Please take the latest pull and check again. If the issue arises again then create a fiddle or plunk and let me know.

**Comment by scozma** [comment]
@sarfarazansari - It seems reinstalling the package (with the last version again) fixes it. Thanks!

**Comment by sarfarazansari** [comment]
@scozma Sounds good!. Thanks for using, the plugin.
