### ISSUE TITLE
LinkedIn and Facebook Signin issues

### ISSUE THREAD

**Issue by sreejithcj** [sarfarazansari/ng4-social-login#6]
I am using ng4-social-login in my Angular 4 project for LinkedIn and Facebook login.
Please see my issues/questions below:

1. Facebook

SignIn happens, but I am not getting notified inside 
ngOnInit() {
    this.authService.authState.subscribe((user) => {

I need to manually refresh the web page with F5 for this to fire. Ideally, I need to be notified on SignIn so that I can redirect the user to my dashboard. How to get it working?

2. LinkeIn

After LinkedIn SIgn In, it refreshes the page and changes the LinkedIn icon to "Welcome <Name>". Can we avoid this? I just need to be notified about LinkedIn Signin so that I can direct the user to dashboard on my own.

Could you please advise?

**Comment by sreejithcj** [comment]
Its working fine for me when I used my custom images for the Facebook and LinkedIn login buttons instead of the official FB and LinkedIn login buttons. I am calling signInWithLinkedIN and signInWithFB when clicking these buttons.

**Comment by sarfarazansari** [comment]
@sreejithcj please try to follow all the steps of provided examples.
