### ISSUE TITLE
Linkedin Signin 401: "[unauthorized]. Expired access token"

### ISSUE THREAD

**Issue by XemaA** [sarfarazansari/ng4-social-login#8]
Hello ! when I click on button linkedin sign in Iget this error: 
GET https://api.linkedin.com/v1/people/~:(id,first-name,last-name,email-address,picture-url) 401 ()

errorCode:0
message:"[unauthorized]. Expired access token. Timestamp: 1511783013193"
requestId:"8APT2XUDE6"
status:401

**Comment by sarfarazansari** [comment]
@XemaA  you have provided a valid token for your app.

**Comment by XemaA** [comment]
hello :) yes my linkedin client id is correct. Today I noticed that the error is fired when I open the login page, so the problem is from the bigining when linkedin is initialised I think !!

**Comment by sarfarazansari** [comment]
@XemaA can you create a jsfiddle or plunkr?
