### ISSUE TITLE
error: "popup_closed_by_user" on google provider

### ISSUE THREAD

**Issue by alex-shmukler** [sarfarazansari/ng4-social-login#9]
Getting this error: "popup_closed_by_user" when i cancel a sign in process on google provider
I found on  Google Sign-In JavaScript client documents: 
popup_closed_by_user - The user closed the popup before finishing the sign in flow.
any suggestions ?

**Comment by sarfarazansari** [comment]
@alex-shmukler Yup when use close the pop-up window without login process completes. this error comes out from Google API Library.

These will be handy if you need any callback.
